# Generated by Django 5.1.2 on 2024-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High')], max_length=50)),
                ('balise', models.CharField(choices=[('Fix', 'Fix'), ('Task', 'Task'), ('Upgrade', 'Upgrade')], max_length=50)),
                ('state', models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Finished', 'Finished')], default='To do', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('devType', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend')], max_length=50)),
                ('deviceType', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=50)),
            ],
        ),
    ]
