# Generated by Django 5.1.2 on 2024-11-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('owner', 'Project Owner'), ('contributor', 'Contributor')], default='contributor', max_length=30),
        ),
    ]
