# Generated by Django 5.1.2 on 2024-11-22 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_contributor_date_joined_contributor_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='projects', through='Project.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
