# Generated by Django 5.1.3 on 2024-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_project_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
